### PR TITLE
Use property definition to normalize read-only event target and which

### LINKED ISSUE #37: Cannot assign to read only property 'target' of object KeyboardEvent and InputEvent
## What is the issue?

Validation and formatting are not triggered because of uncaught errors thrown in the `_eventNormalize` function on keyboard and input events. There is an attempt to assign values to readonly properties. 

This occurs on latest <b>Chrome, Firefox, and Safari.</b>

```javascript
_eventNormalize = function(listener) {
      return function(e) {
        if (e == null) {
          e = window.event;
        }
        e.target = e.target || e.srcElement; // Uncaught TypeError thrown here
        e.which = e.which || e.keyCode; // Uncaught TypeError thrown here too
        if (e.preventDefault == null) {
          e.preventDefault = function() {
            return this.returnValue = false;
          };
        }
        return listener(e);
      };
    };
```
<b> Error Log: </b>
```
Uncaught TypeError: Cannot assign to read only property 'target' of object '#<KeyboardEvent>'
    at HTMLInputElement.<anonymous> (payform.js:43)
(anonymous) @ payform.js:43
payform.js:43 Uncaught TypeError: Cannot assign to read only property 'target' of object '#<InputEvent>'
    at HTMLInputElement.<anonymous> (payform.js:43)
```

## How to reproduce the issue?

- Vendor the `payform.js` file
- Reference the file using ES6 `import` (e.g. `import payform from '../vendor/payform.js';`)
- Type a valid a credit card number and notice that the value will not format itself
- See error logs in the browser console

## Discussion

This behaviour only occurs when vendoring the distribution file. No errors are thrown if we install the package via npm and use `require`.

From what I understand, the `_eventNormalize` function was introduced to modify the event for legacy browser support (e.g. IE8). 

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), the `keyCode` attribute is deprecated and should not be used when handling the keyboard event types (e.g. `keydown`) handled in payform.

Here is what I suggest to allow users to vendor payform:
1- Recreate a new event and assign `target` and `which` attributes
2- Drop support for legacy browsers?

What do you think? 🙂

### PR DESCRIPTION
**Pull request by ddayguerrero**
Fixes #37

The following snippets demonstrate the difference between property assignment and definition:

Property assignment (Issue):

[Edit k1254pn7](https://codesandbox.io/s/k5rrn0k07v)

Property definition (Fix):
[Edit define event properties fix](https://codesandbox.io/s/k1254pn7)
## Changes

- Use property definition instead of property assignment to normalize UI keyboard event properties (i.e. `target` and `which`) across major desktop browsers.

### Why introduce these changes?

- Allows `Payform` to be vendored with using ES6 imports
- Solve TypeErrors which were being raised (see #37 for more details).

### How is this achieved?

- ~~Normalize `target` and `which` KeyboardEvent properties definition through the [Object.defineProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) static method.~~

- Since we want to maintain our compatibility with IE8, we create a "synthetic" event object with the necessary properties used throughout `Payform`. 

### Additional Information

1. Section [10.2.1](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code) of the official ES6 specification states that:
>Module code is always strict mode code.

This prevents [assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only) of read-only properties.

2. How is property assignment different from property definition? Why does the former throws errors?

According to Dr. Axel Rauschmayer, there are noticeable [differences](http://2ality.com/2012/08/property-definition-assignment.html) between property definition and assignment. Specifically, when dealing with read-only properties such as `target`:

>Read-only properties in prototypes prevent assignment, but not definition.

### CODE REVIEW

**Comment by jondavidjohn** [comment]
Good work here in explaining the issue!  Unfortunately, it looks like `Object.defineProperty` is not available in legacy browsers like IE8 (for which this code tries to support).

**Comment by ddayguerrero** [comment]
Ah, right! It only work on DOM objects. What do you think about adding a IE8 [polyfill](https://github.com/inexorabletash/polyfill/blob/master/es5.js)?

**Comment by ddayguerrero** [comment]
I made some changes and attempted to create a "synthetic event" object in `_eventNormalize`. This works in IE8, however as you can see I am cherrypicking properties that are used in the listeners.

Here are some of my other attempts:
- Using [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) but no IE8 support.
- Using `var newEvt = new e.constructor(e.type, e)` but no luck in reassigning properties due to `read-only`.

In the process of seeing how React uses their own SyntheticEvents but it seems that IE8 is not supported.

**Comment by ddayguerrero** [comment]
I've looked into how React normalizes some of its properties and unfortunately it does not support IE8.
[SyntheticEvent](https://github.com/facebook/react/blob/aeda7b745d9c080150704feb20ea576238a1b9a1/packages/events/SyntheticEvent.js#L254) uses `Object.create()` to specify properties such as `target`.

Having said, I've tested latest browsers and IE8+. Everything is stable and tests are still passing. As you have mentioned, it is important that we do not leak the visibility of this synthetic event. Shall we need to handle specific event properties in the feature, we can simple assign them.

Let me know what you think!

**Comment by ddayguerrero** [comment]
I've done some browsers tests. I made sure validation and formatting still works and that no TypeErrors are thrown.

Desktop 🖥:
- Latest Chrome ✅
- Latest Firefox ✅
- Latest Safari ✅
- Latest Edge ✅
- IE8 ✅
- IE10 ✅

Mobile 📱:
- iOS Safari and Chrome ✅
- Android Chrome and Firefox ✅

**Comment by arthurgouveia** [comment]
Code looks good to me and also was able to see the problem was solved

**Comment by jondavidjohn** [comment]
@ddayguerrero Thanks for this, I changed the target branch to `develop` and looks like there is a conflict that needs to be resolved.

(and thanks @arthurgouveia for the second set of eyes!)

**Comment by ddayguerrero** [comment]
Thanks for taking your time @jondavidjohn, I solved the conflicts and did a manual sanity test on changes with `develop` on this [sample](https://codesandbox.io/s/w22ml8rzvl).

Let me know if anything!

**Pull request merged**
