### PR TITLE
Add timeout when setting cursor position on android devices

### PR DESCRIPTION
**Pull request by drei01**
Per https://github.com/text-mask/text-mask/pull/400/files

### CODE REVIEW

**Comment by drei01** [comment]
Fixes https://github.com/jondavidjohn/payform/issues/21

**Comment by jondavidjohn** [comment]
Thanks @drei01!

 @stuyam Do you have a way to confirm this indeed fixes #21 ?

**Comment by jondavidjohn** [comment]
@drei01 Do you mind rebasing these changes on `develop` instead?

**Comment by stuyam** [comment]
I will give it a try and get back to you on if this fixes it ASAP! Thanks for the contribution @drei01

**Comment by drei01** [comment]
The only way I was able to confirm this fixes the issue was my own testing on an Android device. It would be good if @stuyam could also confirm.

**Comment by stuyam** [comment]
Seems like the fix hasn't changed the bug. Take a look. This is on Nexus 4 running Android 5.1.1 on chrome 57.

payform-bug

**Comment by stuyam** [comment]
@drei01 your changes in your repo definitely make sense to me. However I tested on a few android devices and now all of the numbers are entering exactly backwards. The caret stays at the front of the text input and all the text trails in reverse at the end of the input.

**Pull request closed without merging**
