### PR TITLE
added elo card support

### PR DESCRIPTION
**Pull request by SolidLink**
Added Elo card number support. Elo is a major Brazilian debit card.

### CODE REVIEW

**Comment by jondavidjohn** [comment]
Interesting, could you link me to some documentation that lays out the formatting rules?

**Comment by SolidLink** [comment]
Here you go :)
https://www.ebanx.com/business/en/developers/api-reference/payment-reference/validation-rules

**Comment by SolidLink** [comment]
@jondavidjohn Any thoughts on this?

**Comment by jondavidjohn** [comment]
@SolidLink While I have no personal experience with ELO, looks like it's pretty spelled out formatting wise, and it doesn't break any of our other formatting specs. 👍

**Comment by SolidLink** [comment]
Thanks I have been using it in brazil no issues

**Pull request merged**
