### PR TITLE
Added short format expiryInput option

### PR DESCRIPTION
**Pull request by stuyam**
The _validateCardExpiry_ payform method with validate both long (04/2016) and short (04/16) form expiration dates. This pull request added the ability for the expiryInput to format with the short form.

You pass through _true_ as an optional parameter like:

``` javascript
var input = document.getElementById('expiry');
payform.expiryInput(input, true);
```

This will require the input to be **04/16** instead of the long form **04/2016**.

We use the short form at work (@Dockwa) so we use a forked version of Payform for our app. I thought I would make a pull request to hopefully help others looking for the same functionality -> @vinceprofeta https://github.com/dockwa/payform/commit/6cbce4eb90ef557b913e5b2e3843d0d46e3fa901

Also HEADS UP: It looks like I changed a lot more code than I did because when the jQuery version recompiled with my changes it also changed a lot of other things. It seems like the last release of Payform did not recompile the jQuery version because all of the 1.2.0 updates seem to be added when I compiled.

❤️ Stuart

### CODE REVIEW

**Comment by yamartino** [comment]
I am open to discussion on the API itself, the options I was thinking about was:

**the current way, and the more "vanilla js" way**
```javascript
payform.expiryInput(input, true);
```

**more explicit and the more "jQuery" way**
```javascript
payform.expiryInput(input, {short: true});
```

**not a fan of this option but thought I would throw it out there. I don't like it being a seperate method because it is really the exact same thing it just resticts the length different so I think making them seperate is weird to me**
```javascript
payform.expiryInputShort(input);
```

I thought the first option was the most minimal and simplest approach which is why I did it that way, but open to opinions and any additional implementations it could be in 😄

**Comment by jondavidjohn** [comment]
I apologize, I'm likely missing the point, but we currently allow for short year input.  That's what the example page does.

**Comment by yamartino** [comment]
@jondavidjohn that is true it does allow for short 2 year input. However, it does not allow to restrict to the short year input. For example where I work at @Dockwa we wanted to restrict to mm/yy format and not allow for mm/yyyy format. We could obviously figure out if they put in the mm/yyyy format and parse it out properly but this would just allow your to restrict the length to a short format.

**Comment by yamartino** [comment]
Basically either restricting the digits to 6 for mm/yyyy format and 4 digits for the mm/yy format if you pass in _true_ for the short format. I'm not sure if I am explaining this clearly haha

**Comment by jondavidjohn** [comment]
No I think I understand now, you actually want to restrict to 2 digits and disallow 4 digit years.

Yeah, I'm not sure...  Seems like a fringe case to change a method signature for, have you looked into [parseCardExpiry](https://github.com/jondavidjohn/payform#payformparsecardexpirystring) and see if it makes sense to parse/replace it that way?

Is there a particular reason you're not accepting either/or since we provide the same result with `parseCardExpiry`?

**Comment by jondavidjohn** [comment]
In [the example](https://jondavidjohn.github.io/payform/) we set the expectation of a 2 digit year, but it doesn't break if someone enters a 4 digit.

**Comment by yamartino** [comment]
Yeah for sure. The reason we wanted to restrict it was to have no confusion about the format, I know it might sound crazy, and it may just be our user base, but some people were confused and wondering why the placeholder was 'mm/yy' but they could type in '02/2019' and they would contact support before even trying to submit the credit card. We could have just used the 'mm/yyyy' placeholder text but most credit cards use the 'mm/yy' format and it is more concise so we thought there would be no ambiguity with having the placeholder text as 'mm/yy' and restricting to only 4 characters.

Also I made the short form completely optional so it doesn't change the method signature unless you want to require short form. I could totally use the parseCardExpiry function but it is more an issue of UX for the user.

I would love to hear what @vinceprofeta has to say about his needs to wanting to restrict it to short form.

Thanks for hearing me out @jondavidjohn, I totally hear where you are coming from not wanting to make changes like this. Expiry dates are the only parts of the card data that can have different formats so to me it makes sense to allow that functionality, but part of me does also agree with you. That's why I made it an optional add on.

**Comment by jondavidjohn** [comment]
You could possibly make the placeholder 
```
"  /    "
```
without any month or year indicators which would leave it open to interpretation, both of which would turn out correct?

Just a suggestion, I know it's outside the scope of this lib, but just a free thought, worth exactly what you paid for it 😆

**Comment by yamartino** [comment]
@jondavidjohn I respect that! No harm no foul. Also thanks for the work you have done on Payform, works really great for us in our react app, really slick 😄

**Comment by zhil** [comment]
short option doesnt work for me, so I patched it with code like

```
$('#cc-expiration-date').on('keydown', function (event) {
            if ($(this).val().length > 6) {
                event.preventDefault();
                event.stopPropagation();
            }
        });
```

**Pull request closed without merging**
